[package]
name = "spinifex-unsigned-varint"
version = "0.0.1"
authors = ["jmcph4 <jmcph4.github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.17.3"

